language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install matplotlib
# command to run tests
script:
# - pytest # or py.test for Python versions 3.5 and below
  - python SplitBFriends.py -h
  - python SplitBFriends.py -h -f